--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AssassinGhostYT/Particles
build-by-default: true
branches:
- main
projects:
  Particles:
    path: ""
    icon: icon.png
    libs: []
    lint:
      phpstan: false
...
 
